### ISSUE TITLE
Renaming master branch to main

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-swift#1]
Hi @chrispomeroyhale,

We're doing this renaming org-wide as per https://github.com/frictionlessdata/project/issues/537. Can you please take a look?

It's as easy as updating the branch name here - https://github.com/frictionlessdata/schema-collaboration/settings/branches - no more actions on Github are needed.

**Comment by chrispomeroyhale** [comment]
I've pushed a `main` branch although I am not able to change this project's default branch. Is this something you can do @roll and then I'll remove the `master` branch?

**Comment by roll** [comment]
Thanks @chrispomeroyhale!

I didn't want to do so without checking with you but hadn't known that the `maintainer` permissions are not enough for this.

It's now done for both repos :+1:
